---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
        opencensus:
    exporters:
        logging:
            loglevel: debug
        opencensus:
          endpoint: "otel-collector:55678"
          insecure: true
    processors:
        batch:
        queued_retry:
        k8s_tagger:
          passthrough: true
          auth_type: "kubeConfig"
          filter:
            node_from_env_var: KUBE_NODE_NAME
          extract:
            metadata:
              # extract the following well-known metadata fields
              - podName
              - podUID
              - deployment
              - cluster
              - namespace
              - node
    extensions:
        health_check:
    service:
        extensions: [health_check]
        pipelines:
            traces:
                receivers: [opencensus]
                processors: [batch, queued_retry]
                exporters: [opencensus,logging]
            metrics:
                receivers: [opencensus]
                processors: [k8s_tagger]
                exporters: [opencensus,logging]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  labels:
    app: opentelemetry
    component: otel-agent
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-agent
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-agent
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-agent-config.yaml"
          - "--mem-ballast-size-mib=165"
        image: otel/opentelemetry-collector-contrib:0.6.0
        name: otel-agent
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
        ports:
        - containerPort: 8888
          hostPort: 8888

        - name: opencensus
          containerPort: 55678
          hostPort: 55678 # accessible to the cluster pods at <HOST>:55678
          protocol: TCP

        - name: opentelemetry
          containerPort: 55680

        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-agent-config.yaml
          name: otel-agent-config-vol
