---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      opencensus:
      prometheus:
          config:
              scrape_configs:
              - job_name: 'kubernetes-pods'
                scrape_interval: 30s

                kubernetes_sd_configs:
                - role: pod

                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_container_port_name]
                    action: keep
                    regex: (.*-metrics)

                  - action: labelmap
                    regex: __meta_kubernetes_pod_label_(.+)

                  - source_labels: [__meta_kubernetes_namespace]
                    action: replace
                    target_label: kubernetes_namespace

                  - source_labels: [__meta_kubernetes_pod_name]
                    action: replace
                    target_label: kubernetes_pod_name

                  - source_labels: [__meta_kubernetes_pod_container_name]
                    action: replace
                    target_label: kubernetes_container_name

                  - source_labels: [__meta_kubernetes_pod_host_ip]
                    action: replace
                    target_label: kubernetes_pod_host_ip

                  - source_labels: [__meta_kubernetes_pod_label_name]
                    action: replace
                    target_label: app

                 # - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                 #   action: keep
                 #   regex: true
                 #
                 # - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                 #   action: replace
                 #   target_label: __scheme__
                 #   regex: (https?)
                 #
                 # - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                 #   action: replace
                 #   target_label: __metrics_path__
                 #   regex: (.+)
                 #
                 # - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                 #   action: replace
                 #   regex: ([^:]+)(?::\d+)?;(\d+)
                 #   replacement: $1:$2
                 #   target_label: __address__
                 #

    processors:
      batch:
      memory_limiter:
        ballast_size_mib: 500 # Same as --mem-ballast-size-mib CLI argument
        limit_mib: 850        # 80% of maximum memory up to 2G
        spike_limit_mib: 512  # 25% of limit up to 2G
        check_interval: 5s
      queued_retry:
      filter:
        metrics:
          include:
            match_type: regexp
            metric_names:
              - otelcol_.*
              - flask_app.*
              - custom_metric_example
      k8s_tagger:
        auth_type: "kubeConfig"
        extract:
          metadata:
            # extract the following well-known metadata fields
            - podName
            - podUID
            - deployment
            - cluster
            - namespace
            - node
      # tail_sampling:
      #   decision_wait: 5s
      #   num_traces: 50000 # number of traces kept in memory
      #   policies:
      #     - name: all-traces
      #       type: rate_limiting
      #       rate_limiting:
      #         spans_per_seconds: 10
    exporters:
      logging:
        loglevel: debug
      stackdriver:
        resource_mappings:
        - source_type: source.global
          target_type: gke_container
    extensions:
      health_check:
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [opencensus]
          processors: [memory_limiter, k8s_tagger, batch, queued_retry]
          exporters: [logging, stackdriver]
        metrics:
          receivers: [opencensus, prometheus]
          processors: [memory_limiter, k8s_tagger, filter]
          exporters: [logging, stackdriver]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: opencensus
    port: 55678
    targetPort: 55678

  - name: otel-metrics
    port: 8888

  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
          - "--mem-ballast-size-mib=500"
        image: otel/opentelemetry-collector-contrib:0.6.0
        name: otel-collector
        resources:
          limits:
            cpu: 1500m
            memory: 1500Mi
          requests:
            cpu: 400m
            memory: 400Mi
        ports:
        - name: otel-metrics
          containerPort: 8888

        - name: opencensus
          containerPort: 55678

        - name: opentelemetry
          containerPort: 55680

        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
#        - name: otel-collector-secrets
#          mountPath: /secrets
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
#        - secret:
#            name: otel-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - statefulsets
  - replicasets
  - daemonsets
  - deployments
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
