apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: custom-metrics-example
  labels:
    name: custom-metrics-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: custom-metrics-example
  template:
    metadata:
      name: custom-metrics-example
      labels:
        name: custom-metrics-example
    spec:
      containers:
        - name: custom-metrics-example
          image: gcr.io/rnm-datadog-sd/custom-metrics-example:v1.0.3
          ports:
            - containerPort: 55678
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          env:
            - name: DEBUG_MODE
              value: "1"

            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP

            - name: OTEL_AGENT_ENDPOINT
              value: $(OTEL_AGENT_HOST):55678
