apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: custom-metrics-example
  labels:
    name: custom-metrics-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: custom-metrics-example
  template:
    metadata:
      name: custom-metrics-example
      labels:
        name: custom-metrics-example
    spec:
      containers:
        - name: custom-metrics-example
          image: custom-metrics-example
          ports:
            - containerPort: 55678
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 128Mi
          env:
            - name: DEBUG_MODE
              value: "1"

            # OTEL Agent host / ip
            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP

            - name: OTEL_AGENT_ENDPOINT
              value: $(OTEL_AGENT_HOST):55678

            # Metric & resource labels
            - name: CONTAINER_NAME
              value: flask-app-tutorial

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
