---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: flask-app-tutorial
  name: flask-app-tutorial
  namespace: default
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: app
    nodePort: 32424
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    name: flask-app-tutorial
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: statsd-exporter
  name: statsd-exporter
  namespace: default
spec:
  ports:
    - name: statsd-metrics
      protocol: TCP
      port: 9102
      targetPort: 9102
  selector:
    name: flask-app-tutorial
  sessionAffinity: None
