---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-app-tutorial
  labels:
    name: flask-app-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-app-tutorial
  template:
    metadata:
      name: flask-app-tutorial
      labels:
        name: flask-app-tutorial
    spec:
      containers:
        - name: flask-app-tutorial
          image: gcr.io/rnm-datadog-sd/flask-app:latest
          ports:
            - name: flask-metrics
              containerPort: 9090
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"

        - name: statsd-exporter
          image: prom/statsd-exporter
          args: ["--log.level=debug"]
          imagePullPolicy: Always
          ports:
          - name: statsd-metrics
            containerPort: 9102

          - containerPort: 9125
            protocol: UDP
