---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-app-tutorial
  labels:
    name: flask-app-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-app-tutorial
  template:
    metadata:
      name: flask-app-tutorial
      labels:
        name: flask-app-tutorial
    spec:
      containers:
        - name: flask-app-tutorial
          image: gcr.io/rnm-datadog-sd/flask-app:latest
          ports:
            - containerPort: 8080
            - containerPort: 55678
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: OTEL_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP

            - name: OTEL_AGENT_ENDPOINT
              value: $(OTEL_AGENT_HOST):55678

        - name: statsd-exporter
          image: prom/statsd-exporter
          args: ["--log.level=debug"]
          imagePullPolicy: Always
          ports:
          - name: statsd-metrics
            containerPort: 9102

          - containerPort: 9125
            protocol: UDP
